python fetch_categories_mp.py 0 &
python fetch_categories_mp.py 1 &
python fetch_categories_mp.py 2 &
python fetch_categories_mp.py 3 &
python fetch_categories_mp.py 4 &
python fetch_categories_mp.py 5 &
python fetch_categories_mp.py 6 &
python fetch_categories_mp.py 7 &
python fetch_categories_mp.py 8 &
